### ISSUE TITLE
amp-next-page not showing following articles 

### ISSUE THREAD

**Issue by mvarat** [analytics-debugger/google-analytics-4-for-amp#10]
Hi David!
I was able to implement your solution but noticed that once the GA4 analytics were set up, amp-next-page no longer showed the following articles. I am still seeing amp-next-page-links. This was previously working when other amp-analytics tags were set up. Any ideas what is causing this or a work around?
Thanks!

**Comment by thyngster** [comment]
As far as I'm concerned this doesn't interfere with any other AMP plugins at all. If you could share a link something i could take a look.

**Comment by mvarat** [comment]
Here is a link to a test AMP article including the GA4 analytics script: https://qa.purewow.net/fashion/how-to-wear-ballet-flats/amp. Here is the same article without it where amp-next-page is working properly: https://staging.purewow.net/fashion/how-to-wear-ballet-flats/amp.

**Comment by mvarat** [comment]
Hi David, 
The issue is not happening on my local environment so I am pretty sure it has something to do with the QA environment and not amp-analyitics. Thanks for your time!
