### ISSUE TITLE
File not found getting 404 as we add this script 

### ISSUE THREAD

**Issue by kapilgp** [analytics-debugger/google-analytics-4-for-amp#11]
After adding 

https://amp.analytics-debugger.com/ga4.json

We found that collect request are working but with that following error also thrown, somehow it tries to load below url but that url not found can you please check how to fix it.

https://cdn.ampproject.org/rtv/012301112346000/v0/analytics-vendors/ampGtmAnalytics.json

**Comment by thyngster** [comment]
That's file is not part of this solution and it's hosted by Google/AMP so I'm afraid you should be asking them... Or review your implementation to see why it's loading that file

**Comment by kapilgp** [comment]
As I remove this script that error also gone,

We used below code to integrate it.

`<amp-analytics type="ampGtmAnalytics" config="https://amp.analytics-debugger.com/ga4.json" data-credentials="include">
            <script type="application/json">
            {
                "vars":{ 
                    "GA4_MEASUREMENT_ID": "<GA4 ID>", 
                    "GA4_ENDPOINT_HOSTNAME": "www.google-analytics.com", 
                    "DEFAULT_PAGEVIEW_ENABLED": true, 
                    "GOOGLE_CONSENT_ENABLED": false, 
                    "WEBVITALS_TRACKING": true, 
                    "PERFORMANCE_TIMING_TRACKING": false, 
                    "SEND_DOUBLECLICK_BEACON": false 
                }
            }
            </script>
        </amp-analytics>`

**Comment by thyngster** [comment]
@kapilgp type="ampGtmAnalytics" that's not a valid value. The docs are pretty explicit. please use type="googleanalytics"
