### ISSUE TITLE
AMP traffic not showing up in DebugView

### ISSUE THREAD

**Issue by jerclarke** [analytics-debugger/google-analytics-4-for-amp#12]
Hi, I have no idea if this is related to using your script or not (I'm using it indirectly through the AIWP wordpress plugin that integrates it) but I figured this was a good place to see if anyone else is suffering the same issue as me:

The GA4 DebugView thing is working for normal traffic on my site, but the AMP traffic never shows up, despite ultimately showing up in the reports such as "Realtime". 

I feel like this was working previously, and when I set it all up I was seeing the AMP traffic there too, so maybe something changed in the last few weeks?

Are others able to see the AMP traffic from this script in DebugView? If you can see it at least I'll know it's something about my setup (could be an issue with the GA Debug Chrome extension, for example).

**Comment by thyngster** [comment]
@jerclarke I can't give support to other people plugins ( even less if they use my work without any mention or attribution and even linking to my CDN ) 

In any case try adding ?_dbg=1 to the current url you're testing to see if it shows up.
