### ISSUE TITLE
How to setup correctly

### ISSUE THREAD

**Issue by firmlab** [analytics-debugger/google-analytics-4-for-amp#13]
Hi, i have two questions regarding this library.

1. In order to use this library do I still need to put the script below on my AMP page?

`<script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>`

2. How can we use this library if I have GTM setup with GA4 ?

Really appreciate to anyone who can respond to my question.

Thank you

**Comment by thyngster** [comment]
Yep, you still need the analytics library, and this meant to be a native GA4 tracking for AMP. I don't think GTM AMP currently supports GA4 tags.
