### ISSUE TITLE
How to disable debug mode and extraurlParamsReplaceMap

### ISSUE THREAD

**Issue by kapilgp** [analytics-debugger/google-analytics-4-for-amp#14]
Hi,

We have implemented this script and after that we can see increase user into GA4 Dashboard but there is no impact in page_view.

So I have doubt that is it due to debug mode and extraurlParamsReplaceMap,

So can you please tell us that how we can configure it, so there is no key __dbg=1 and extra variables should go with **ep.**
 prefix, as I found that there is already mapping into your file but don't have an exact idea how we can use that one.

```
 "extraUrlParamsReplaceMap": {
    "user__str_": "up.",
    "user__num_": "upn.",
    "event__str_": "ep.",
```

**Comment by thyngster** [comment]
I don't really get the issue here and why there's any need to remove some key features. Just grab the ga4.json remove whatever you need from it and host it on your own server.
