### ISSUE TITLE
"Access to fetch from origin has been blocked by CORS policy" with self-hosted ga4.json

### ISSUE THREAD

**Issue by SergeZ23** [analytics-debugger/google-analytics-4-for-amp#16]
Hi, thank you for this repository!
We've hosted the ga4.json on our website as described in the article, but I'm getting the following error:
![image](https://user-images.githubusercontent.com/85741793/224318906-acb7e737-c966-4915-b116-403ed0808a84.png)
How can I fix this?

**Comment by thyngster** [comment]
If you're hosting it yourself on a different origin than the requesting domain, you should setup the CORS headers accordinly. You should be talking with your IT Team to assist you with this. Should be pretty straighforward for them to check the error and came back with a fix  :O
