### ISSUE TITLE
Sometimes https://amp.analytics-debugger.com/ga4.json is not available

### ISSUE THREAD

**Issue by IT-Cru** [analytics-debugger/google-analytics-4-for-amp#17]
From time to time it seems that loading https://amp.analytics-debugger.com/ga4.json file throws a CF host error page. So for all who use it directly from https://amp.analytics-debugger.com could loose tracking events on AMP for their pages.

Idea: Maybe CF caching setup could be improved for ga4.json file, because I think this JSON file is nearly static and could be provided with `cache-control: max-age=31536000, public` header from host to cache it longer on CF itself without any requests to host system.

CF settings should respect provided cache-control headers for expiration to cache this up to 1 year. For browsers it should be not cached so long via a CF page rules.

When ga4.json file gets changed on host system this URL needs to be purged. This could be maybe done automatically via CF API purge requests.

I think it also depends on related CF setup for https://www.analytics-debugger.com when they are running under same CF account.

Let me know, if I could help here somehow with my CF knowledge from other projects :)

**Comment by thyngster** [comment]
Hi, I'm so sorry about this, the ISP turned down the servers on 23th because I'm traveling and my credit card was deactivated for too many charges overseas ... It took me almost 2 days to solve this. 

Things should be up in some hours, and I'm in talk with the provider to change the payment method so they just take to money each month to avoid this kind of issues.

My apologies, being travelling abroad makes things a bit difficult somethings  ...

**Comment by thyngster** [comment]
Service has been restored 07:47pm JSP. I've added an extra failover server located on a different provider and I'm also taking the needed steps to have the servers paid from my bank account rather from my credit card to avoid this kind of issues in the future.

I'm also adding some internal monitoring to get notified on any issues on the service in the future via Slack/SMS. 

My apologies for this service interruption.

**Comment by thyngster** [comment]
Added a monitoring page here: 
https://status.analytics-debugger.com/

**Comment by IT-Cru** [comment]
@thyngster thx for fast fixing and enjoy your traveling :)

I will also investigate if it is possible to host your ga4.json file as CF pages with some optimized CF cache settings. Maybe than no extra host servers are required and/or as alternative solution for others who need/want to integrate it without usage of your service.

**Comment by thyngster** [comment]
It's already cached by CF, but if the edge goes down too much time ... 

We should be ok tho. I'm closing this for now
