### ISSUE TITLE
Reporting ampdocHost for AMP cache hits

### ISSUE THREAD

**Issue by dgilman** [analytics-debugger/google-analytics-4-for-amp#19]
For GA3 it was possible to send back the AMP hostname to let you distinguish between hits served by the AMP cache and hits served by your servers. See "Cache vs. non-cache analysis" on [this page](https://support.google.com/analytics/answer/6343176) in the official docs.

It looks like it was just setting a custom dimension and sending that back. First, it may be possible to set the hostname dimension directly - if so, could ga4.json do that? If not, could you document if it's ok to set the cdX fields with GA4 like it was with GA3?

**Comment by thyngster** [comment]
You have several examples about how passing event parameters and user properties on my blog. That should allow you to cover your needs

**Comment by thyngster** [comment]
hi @dgilman this is now available a parameter names "amp_hostname" is now sent within the hit. You'll need to map it as a dimension in your property.
