### ISSUE TITLE
Extra Steps for Engagement Time Tracking (&_et)?

### ISSUE THREAD

**Issue by kevingilbert100** [analytics-debugger/google-analytics-4-for-amp#2]
Are there any extra steps required to get the Engagement Time Tracking (&_et) working? I've gotten scroll-depth working and generic page view events... but the AMP page doesn't seem to track time on page.

**Comment by thyngster** [comment]
I really though I published this, it seems i didn't commit it. I willl update it in a bit.

**Comment by thyngster** [comment]
It's already tested.
I'm updating the docs.

![image](https://user-images.githubusercontent.com/1494564/182704852-f46e6dbf-dee4-40e7-8f46-1ddf11516abc.png)

**Comment by kevingilbert100** [comment]
Amazing!!

**Comment by kevingilbert100** [comment]
Do you just do this with a timer event?

**Comment by thyngster** [comment]
Kevin, I'm adding some other features like debug mode and regional data collection  and I'll need to test this a bit more deeper. Will do the pull request before EOW.

**Comment by kevingilbert100** [comment]
Amazing, let me know if I can help.

**Comment by thyngster** [comment]
Updates are now merged and the new config version deployed into the CDN.

**Comment by kevingilbert100** [comment]
Is there a way to capture active engaged time with this? So continuously pinging GA every x seconds rather than just on scroll events/etc? - Maybe using a timer?
