### ISSUE TITLE
Support for e-commerce events

### ISSUE THREAD

**Issue by kborisov93** [analytics-debugger/google-analytics-4-for-amp#23]
Does this configuration support [e-commerce events](https://developers.google.com/analytics/devguides/collection/ga4/ecommerce?client_type=gtag), like item_view and add_to_cart?
I tried setting them up like custom events but couldn't make them work.

**Comment by ipixel** [comment]
@kborisov93 we are running into this same thing at the moment, did you manage to solve this and work in support for ecommerce events?

**Comment by kborisov93** [comment]
Yes, you can add them directly in the triggers object. My configuration looks like this:

`"triggers": {
				    "view_item": {
				        "enabled": true,
					    "on": "visible",
					    "request": "ga4Event",
					    "vars": {
					        "ga4_event_name": "view_item"
					    },
					     "extraUrlParams": {
					        "event__str_item_id": "<?php echo $product->get_sku() ?>",
							"event__str_item_name": "<?php echo $product->get_title() ?>",
							"event__str_item_category": "<?php echo get_primary_product_category( $product->get_id() ) ?>",
							"event__num_price": "<?php echo $product->get_price() ?>"
					    }
				    },
				    "add_to_cart": {
				        "enabled": true,
					    "on": "click",
					    "selector": "#buy-product input[type=submit]",
					    "request": "ga4Event",
					    "vars": {
					        "ga4_event_name": "add_to_cart"
					    },
					      "extraUrlParams": {
					         "event__str_item_id": "<?php echo $product->get_sku() ?>",
							"event__str_item_name": "<?php echo $product->get_title() ?>",
							"event__str_item_category": "<?php echo get_primary_product_category( $product->get_id() ) ?>",
							"event__num_price": "<?php echo $product->get_price() ?>"
					    }
				    }`
