### ISSUE TITLE
I cannot measure the average interaction time correctly

### ISSUE THREAD

**Issue by javier-dcip** [analytics-debugger/google-analytics-4-for-amp#27]
Good morning, everyone. I don't know if it's happening to anyone else, but in our projects that I've added this solution to measure AMP pages with GA4, I can't get the average interaction time to give reliable results. It always gives me results of a few seconds (1 second, 2 seconds, etc).

I think it's because of some server configuration, but I can't see where the problem is.
If you can give me more information about how this meter works and what parameters I should look at I would appreciate it.

Thanks and best regards.

**Comment by thyngster** [comment]
If you don't have more events than the page_view that's normal. There's no engamenet tracked at all on the pages navigation. ( will be in the next release, I guess ... )

**Comment by thyngster** [comment]
@javier-dcip I've just published a new released that should properly track the engagment time
