### ISSUE TITLE
AmpAnalytics <unknown id>] Error loading remote config

### ISSUE THREAD

**Issue by csonrel** [analytics-debugger/google-analytics-4-for-amp#29]
Hello, 

I'm sorry to have to bother you with this, but I'm having a problem on one of my sites with an error "AmpAnalytics <unknown id>] Error loading remote config"

The Json file is hosted on our servers. 

https://www.bymycar.fr/webzine/nos-concessions-ford-bymycar-connectees/amp/

Thank you very much

**Comment by thyngster** [comment]
This is not the way AMP work, you should review the AMP documentation. config attribute is mean to hold a remote/local file url. You either do it that way or just put the content within the amp analytics tags content.
