### ISSUE TITLE
Error on console: AmpAnalytics <unknown id>: No triggers were found in the config. No analytics data will be sent.

### ISSUE THREAD

**Issue by cirofeitosa** [analytics-debugger/google-analytics-4-for-amp#31]
Hello,

We implemented the `amp-analytics` tag with self-hosted JSON config, as below:

```
<amp-analytics type="gtag" config="https://www.ourdomain.com/ga4.json" data-credentials="include">
	<script type="application/json">
	{
		"vars": {
			"GA4_MEASUREMENT_ID": "G-OUR-ID-HERE",
			"GA4_ENDPOINT_HOSTNAME": "www.google-analytics.com",
			"DEFAULT_PAGEVIEW_ENABLED": true,
			"GOOGLE_CONSENT_ENABLED": false,
			"WEBVITALS_TRACKING": false,
			"PERFORMANCE_TIMING_TRACKING": false,
			"SEND_DOUBLECLICK_BEACON": false,
			"DISABLE_REGIONAL_DATA_COLLECTION": false,
			"ENHANCED_MEASUREMENT_SCROLL": false
		}
	}
	</script>
</amp-analytics>
```

Everything is loading, including the self-hosted JSON.

<img width="1013" alt="Screenshot 2023-06-07 at 11 08 04" src="https://github.com/analytics-debugger/google-analytics-4-for-amp/assets/115043/4a01d9ef-860c-45a2-8d14-3c64d3b810d2">
<img width="572" alt="Screenshot 2023-06-07 at 11 07 55" src="https://github.com/analytics-debugger/google-analytics-4-for-amp/assets/115043/cbf2d2dc-f3b8-4f03-b7e2-f43f1de3a225">

But on console appears this warning:

```
v0.js:2 [AmpAnalytics <unknown id>] No triggers were found in the config. No analytics data will be sent.
```

<img width="692" alt="Screenshot 2023-06-07 at 11 08 27" src="https://github.com/analytics-debugger/google-analytics-4-for-amp/assets/115043/37c1c0cb-6722-46d8-a74e-c547c6b30f4d">

Anyone know how to solve this problem?

**Comment by thyngster** [comment]
That snippet is wrong, the type should  type="googleanalytics"  not   type="gtag"  as it's defined on the documentation.
