### ISSUE TITLE
Adsense tracking with GA4 AMP

### ISSUE THREAD

**Issue by punisher0** [analytics-debugger/google-analytics-4-for-amp#33]
Hello,

When I use Google Analytics 4 AMP code

`<amp-analytics type="googleanalytics" config="https://amp.analytics-debugger.com/ga4.json" data-credentials="include">
<script type="application/json">
{
    "vars": {
                "GA4_MEASUREMENT_ID": "G-THYNGSTER",
                "GA4_ENDPOINT_HOSTNAME": "www.google-analytics.com",
                "DEFAULT_PAGEVIEW_ENABLED": true,    
                "GOOGLE_CONSENT_ENABLED": false,
                "WEBVITALS_TRACKING": false,
                "PERFORMANCE_TIMING_TRACKING": false,
                "SEND_DOUBLECLICK_BEACON": false
    }
}
</script>
</amp-analytics> `

When I'm using the AMP GA4 code, it doesn't show Adsense data (click, ad unit, impressions, etc.), but it works fine if I use the simple code.

Any help with this?

Thanks

**Comment by thyngster** [comment]
Adsense is not part of the GA4 tracking.
