### ISSUE TITLE
Setting other gtag parameters 

### ISSUE THREAD

**Issue by nmd2w** [analytics-debugger/google-analytics-4-for-amp#6]
How about setting other gtag parameters like page_title, page_location. Could you show us the correct way of achieving this in your configuration please.

**Comment by nmd2w** [comment]
Hi @thyngster,

Happy that you are working on it. Thanks.

Could you please put a quick reply here on this, before you planning the next version, if possible.

**Comment by pabloaugusto** [comment]
Any news?

**Comment by thyngster** [comment]
@nmd2w @pabloaugusto this is now possible on the last merged version!
use OVERRIDE_PAGE_LOCATION and OVERRIDE_PAGE_TITLE variables to override these values.
