### ISSUE TITLE
CDN is not able to find ga4.json file hosted on my server

### ISSUE THREAD

**Issue by fahedyasin** [analytics-debugger/google-analytics-4-for-amp#8]
Hi David!
We used this solution, and we are able to see page_view data in GA4 for AMP pages, but we are facing an issue regarding a lesser number of page views. We hosted the `ga4.json` file on our own server.

Upon doing some investigation, we found out that have found out that AMP articles served from google cache under the http://ampproject.org/ domain are throwing js errors and GA4 collects are not being sent.
<img width="891" alt="Screenshot 2022-12-12 at 02 29 11" src="https://user-images.githubusercontent.com/5945904/207321285-043aa730-f756-46e5-86f1-850af5b61bb8.png">

Somehow, the `ga4.json` is not being cached/served from CDN on ampproject.

Can you please help us here as you have already successfully hosted it on CDN.

**Comment by IT-Cru** [comment]
@fahedyasin have you maybe used a relative instead of an absolute URL to your ga4.json file on your own server in your amp-analytics tag?

This could be a possible problem in your setup, because this file with relative path doesn't exists on Google AMP cache.

**Comment by thyngster** [comment]
Since there has not been more updated I'm closing the issue.

**Comment by fahedyasin** [comment]
@IT-Cru yes, that was the actual problem. Changing the relative path to absolute fixed the issue. Thank you.
