### ISSUE TITLE
tag the repo with version numbers for cdnjs to host the ga4.json file

### ISSUE THREAD

**Issue by irvin** [analytics-debugger/google-analytics-4-for-amp#9]
I had file an issue on cdnjs to host the project, and they require this repo to be tagged with release version numbers, so that they can automatically fetch and update the file
https://github.com/cdnjs/packages/issues/1411#issuecomment-1345616868

**Comment by thyngster** [comment]
Hi @irvin it's currently going through CloudFlare, I tried to sort this before with jsdelivr, but in order to have this worker this needs to be served with some CORS headers, which is something not supported by any js/json CDN I checked ( at least out of the box )

**Comment by irvin** [comment]
oh yes, that's the difficult part.
